################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_bright.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_eco.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_hue.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_pc.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_tel.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_wifi.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_cloud.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_copy.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_internet.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_mobile.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_no_internet.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_phone.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_print.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_printer2.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_ready.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan_example.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_setup.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_usb.c \
../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_wave.c 

OBJS += \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_bright.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_eco.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_hue.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_pc.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_tel.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_wifi.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_cloud.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_copy.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_internet.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_mobile.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_no_internet.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_phone.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_print.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_printer2.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_ready.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan_example.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_setup.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_usb.o \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_wave.o 

C_DEPS += \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_bright.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_eco.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_hue.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_pc.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_tel.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_wifi.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_cloud.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_copy.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_internet.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_mobile.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_no_internet.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_phone.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_print.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_printer2.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_ready.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan_example.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_setup.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_usb.d \
./Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_wave.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_bright.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_bright.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_bright.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_eco.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_eco.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_eco.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_hue.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_hue.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_hue.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_pc.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_pc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_pc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_tel.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_tel.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_tel.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_wifi.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_wifi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_icon_wifi.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_cloud.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_cloud.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_cloud.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_copy.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_copy.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_copy.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_internet.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_internet.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_internet.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_mobile.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_mobile.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_mobile.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_no_internet.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_no_internet.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_no_internet.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_phone.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_phone.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_phone.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_print.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_print.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_print.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_printer2.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_printer2.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_printer2.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_ready.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_ready.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_ready.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan_example.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan_example.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_scan_example.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_setup.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_setup.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_setup.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_usb.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_usb.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_usb.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_wave.o: ../Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_wave.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32H743xx -DDEBUG -c -I../Core/Inc -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/delay" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/sys" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/24CXX" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/IIC" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/LCD" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/TOUCH" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib" -I"D:/code/STM32_WorkSpace/h743LCD/Core/Lib/lvgl" -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Lib/lvgl/lvgl_examples/src/lv_demo_printer/images/lv_demo_printer_img_wave.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

